---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "smitbackendapi"
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "smitbackend-config-jdkz"
  namespace: "smitbackendapi"
  labels:
    app: "smitbackend"
data:
  MONGO_URL: "mongodb+srv://smit:9099850857@cluster0.srki2ok.mongodb.net/?retryWrites=true&w=majority"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "smitbackend"
  namespace: "smitbackendapi"
  labels:
    app: "smitbackend"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "smitbackend"
  template:
    metadata:
      labels:
        app: "smitbackend"
    spec:
      containers:
      - name: "smitbackend-1"
        image: "gcr.io/smitbackend/smitbackend:latest"
        ports:
          - containerPort: 8080
        env:
        - name: "MONGO_URL"
          valueFrom:
            configMapKeyRef:
              key: "MONGO_URL"
              name: "smitbackend-config-jdkz"
---
apiVersion: "autoscaling/v2beta2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "smitbackend-hpa-wogk"
  namespace: "smitbackendapi"
  labels:
    app: "smitbackend"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "smitbackend"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

