name: Docker Build and Run

on:
  push:
    branches:
      - main # Change this to your main branch name

env:
  DOCKER_USER: '${{secrets.DOCKER_USERNAME}}'
  DOCKER_PASSWORD: '${{secrets.DOCKER_PASSWORD}}'
  MONGO_URL: '${{secrets.MONGO_URL}}'
  GCP_SA_KEY: '${{secrets.SERVICE_ACCOUNT_KEY}}'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Directory
        run: ls -a


      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: '${{secrets.DOCKER_USERNAME}}'
          password: '${{secrets.DOCKER_PASSWORD}}'

      - name: Docker Login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build Docker Image
        run: |
          docker build -t smitbackend:latest .

      - name: Docker Tag
        run: docker tag smitbackend:latest $DOCKER_USER/smitbackend:latest

      - name: List Images
        run: docker images

      - name: Docker Push
        run: docker push smitmark01/smitbackend:latest

      - name: Run Docker Container
        run: |
          docker run -d -e MONGO_URL=$MONGO_URL -p 8080:8080 --name smitbackend smitbackend:latest

  IOC:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:


      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}


      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
            credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'



      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: List Project
        run: gcloud projects list | gcloud config get-value project

      - name: Build Docker Image
        run: |
          docker build -t smitbackend:latest .

      - name: Install Terraform
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list > /dev/null
          sudo apt-get update && sudo apt-get install terraform | terraform --version | docker images

